### ISSUE TITLE
[Maybe] A command to create an API key

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#10]
Something like this:

```
$ ripe-atlas create-key <permission-name>
```

**Comment by danielquinn** [comment]
The big problem with this one is the fact that key creation needs authentication and authorisation and we don't currently have that ability via the API.  Of course a Dirty Hack could be written to use Mechanize or something, but... *ew*.

So, I'm going to give this issue a week and then mark it as `WONTFIX` unless we can settle on whether or not we want to accommodate this sort of thing at the API level.

**Comment by chrisamin** [comment]
The keys API exists these days so considering this.

**Comment by chrisamin** [comment]
But then again, no
