### ISSUE TITLE
Store cache files for Python 2 and 3 separately

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#106]
Users who have more than one Python instance on their machine will get annoying crashes when trying to run Magellan in one version and then again in another because of how the different versions store data.  A simple work around for this would be to use different cache files based on the Python version.

I'd recommend using `sys` or `six` to determine the Python version, and then just set the local cache file name based on that.  Something like: `${HOME}/.config/ripe-atlas-tools/cache-2.7.db`.

See #105 for more info.

**Comment by astrikos** [comment]
I was about to comment that this would be the best solution for this, if we want to keep it working for both of them. Now we have it as an issue, so it's good
