### ISSUE TITLE
Support shell completion 

### ISSUE THREAD

**Issue by astrikos** [RIPE-NCC/ripe-atlas-tools#113]
It would be useful if we could offer this to people. I think there are some python libs that could implement this easier for us.

**Comment by Jterbeest** [comment]
Something like https://pypi.python.org/pypi/argcomplete/1.0.0 perhaps??

**Comment by danielquinn** [comment]
@Jterbeest looks good!  We do some creative magic with the first argument, so that will have to be looked into, but for the rest of it, I think this sounds like just what we need!
