### ISSUE TITLE
This project needs a codename

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#13]
For practical reasons, it doesn't make sense for us to be promoting this project as anything other than *RIPE Atlas Tools*, but when we're talking about the code itself, statements like "just use the tool" or just "tools" doesn't really play well.

So, let's have a code name for this.  If we're to conform to the other libraries and bits we have out there (Cousteau, Sagan), it should be an explorer.  Post your preferences here and vote with a :+1: if you like.  We'll pick one and I'll put something easter-egg like in there for you all to play with at some point.

**Comment by astrikos** [comment]
Magellan...first circumnavigation of the Earth.

**Comment by ioc32** [comment]
@danielquinn it's Dora time!

**Comment by danielquinn** [comment]
Some other names suggested around the office today:

* Jules
* Voyager
* Janeway
* Picard

**Comment by pierky** [comment]
> Magellan...first circumnavigation of the Earth.

:+1: in memory of those times when RTT was ~3 years.

**Comment by danielquinn** [comment]
I'm leaning toward Magellan... going once, going twice...

**Comment by danielquinn** [comment]
Magellan it is!
