### ISSUE TITLE
ripe-atlas-tools are not compatible with current version of ripe-atlas-cousteau

### ISSUE THREAD

**Issue by rrzefox** [RIPE-NCC/ripe-atlas-tools#139]
Currently, just installing ripe-atlas-tools with `pip --user ripe.atlas.tools`
will lead to a nonfunctional installation. Some commands will work, like
'measurements'. Others, like 'stream' or 'report' will fail with the extremely
irritating error-message `No such command.`. This is caused by the fact that
ripe-atlas-tools is incompatible with the current version 1.1 of
ripe-atlas-cousteau released on Feb 09. 

Manually downgrading the version of ripe-atlas-cousteau to 1.0.7
(`pip install --user ripe.atlas.cousteau==1.0.7`) makes ripe-atlas-tools work
again.

**Comment by astrikos** [comment]
Indeed, that's true last changes were not backward compatible. Probably what's wise is to have an exact version in the setup file and not ">=". For now using 1.0.7 should make the trick as you said and I will make sure we will have the fix with next release.

**Comment by seb-at-nzrs** [comment]
Just to say I got bitten by this issue, tracked it down to the version of ripe.atlas.cousteau. Running the downgrade with pip fixed it.

**Comment by danielquinn** [comment]
With the new releases, does this still apply?

**Comment by astrikos** [comment]
no, it should be fixed :)
