### ISSUE TITLE
The default radius for probe location searches is really small

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#141]
My probe is in my home in London, in Zone 2, which is to say that by comparison to most people living in London, I live pretty close to the centre.  However, the following command renders 0 results:

    $ ripe-atlas probes --location "London"

If you widen the radius to `5` however you get some probes, but still not mine:

    $ ripe-atlas probes --location "London" --radius 5

To get mine, you need to extend the radius to `7`, but even then, you're only getting probes within a 7km radius from London's centre.  Given that most people living in London live up to 25 or even 30km away from the centre, it would appear that the default radius is insufficient.  Indeed, even setting `--radius 1` returns 92 results, so something is fishy there.

**Comment by astrikos** [comment]
Okay we could probably change default to something like 10. I think 25-30 might be too much?
92 results for London for radius 1 you think is too much? why do you think is fishy?

**Comment by danielquinn** [comment]
Using 10 seems reasonable until you consider that most people when they say `city-name`, they mean `city-name and its surrounding areas`.  For example, "Toronto" is a city of 5million spanning much more than 20k, and if you're looking for probes in Toronto, you'd probably want to include stuff in Toronto's suburbs, like Etobicoke and Scarborough.

The tricky part though is that if you apply the same logic to a smaller town, you end up lumping smaller towns together -- though that might be ok considering what you're trying to achieve here: "probes in <city-name>-ish".  So for my money, 10 is too small, and would prefer 15, but if you'd prefer 10 I won't fuss.

As to your second question about `--radius 1`, nevermind that, I was being dumb :-)

**Comment by astrikos** [comment]
I don't really have strong feelings, so I am going to change to 15 as you proposed
