### ISSUE TITLE
"render" and "report" have similar functionality and ambiguous names

### ISSUE THREAD

**Issue by chrisamin** [RIPE-NCC/ripe-atlas-tools#157]
It is not clear from the names of the "render" and "report" commands why they are different, and they do principally do the same thing. IMHO this is made a bit clearer with the extra help text, but there is still room for improvement.

One possible solution would be to merge the commands into one, by e.g. adding stdin reading and a --from-file option to "report" and deprecating "render". Another solution would be to rename one or both of them so that the distinction is clearer, although I think that in that case we should make one an explicit superset of the other because at the moment we have duplicate code.

**Comment by danielquinn** [comment]
> One possible solution would be to merge the commands into one, by e.g. adding stdin reading and a --from-file option to "report" and deprecating "render". 

This was my first thought.  You're totally right and there's no reason to have both commands as they really only confuse people.  As long as `render` is supported for a while with a deprecation warning, I'm cool with this.
