### ISSUE TITLE
New measurement

### ISSUE THREAD

**Issue by sanchezquibus** [RIPE-NCC/ripe-atlas-tools#169]
What should I do if I want a running measurement?
I mean, using Magellan I want to create a running ping with no end. (with no stop time defined)
Doing it by RIPE's web page you are able to set the stop time as never. How can I do it in this ripe tool?
Thanks in advance

**Comment by sanchezquibus** [comment]
I get it

**Comment by astrikos** [comment]
Hi @sanchezquibus, see if [docs](http://ripe-atlas-tools.readthedocs.io/en/latest/quickstart.html#creating-a-measurement) we have helps. If not let me know.
