### ISSUE TITLE
SSL consistency definition

### ISSUE THREAD

**Issue by pierky** [RIPE-NCC/ripe-atlas-tools#17]
Perhaps a better method to determine SSL cert. consistency should be used, maybe the same used on the RIPE Atlas website GUI in order to have consistent results between this cmd line tool and the web GUI?

https://github.com/RIPE-NCC/ripe-atlas-tools/blob/2a447f2f0901077473eb88b9bb53a0619beaf382/ripe/atlas/tools/renderers/ssl_consistency.py#L53

**Comment by danielquinn** [comment]
Currently on the UI, the concept of "consistency" is determined by chaining all of the checksums together and comparing each.  This string is already available in Sagan results by accessing `result.checksum_chain`.  Does that sound ok by you?

**Comment by pierky** [comment]
In my draft implementation I did something similar: I use the SHA256 fingerprint to build a list of unique certificates and then I count how many probes are receiving each certificate, but in the end I'm unsure how to establish if the probe is receiving the expected certificate or an unexpected one.

Msm 1443162 example:

```
{
 u'07:52:BE:65:72:BF:02:D4:C9:E2:93:09:A8:E0:BE:3A:EA:D4:30:41:B8:49:FA:C5:F2:12:33:07:37:57:EE:C7':
   {'cert': <ripe.atlas.sagan.ssl.Certificate object at 0x7fdcbe352590>,
    'cnt': 1,
    'probes': [2844]},
 u'1A:B8:9E:ED:1B:DD:A0:E2:EA:67:89:C1:C5:4B:20:1C:49:9D:74:27:B0:5D:11:F2:9A:5F:C1:0D:F9:18:48:DA':
   {'cert': <ripe.atlas.sagan.ssl.Certificate object at 0x7fdcbe352610>,
    'cnt': 1,
    'probes': [2844]},
 u'21:EB:37:AB:4C:F6:EF:89:65:EC:17:66:40:9C:A7:6B:8B:2E:03:F2:D1:A3:88:DF:73:42:08:E8:6D:EE:E6:79':
   {'cert': <ripe.atlas.sagan.ssl.Certificate object at 0x7fdcbe3525d0>,
    'cnt': 415,
     'probes': [1000, 10082, ... ]},
 u'36:13:D2:B2:2A:75:00:94:76:0C:41:AD:19:DB:52:A4:F0:5B:DE:A8:01:72:E2:57:87:61:AD:96:7F:7E:D9:AA':
   {'cert': <ripe.atlas.sagan.ssl.Certificate object at 0x7fdcbe352410>,
    'cnt': 415,
    'probes': [1000, 10082, 10095, 10099, ...]},
 u'6D:5B:C9:79:46:1C:72:64:E1:71:00:10:CD:7D:4E:A3:EC:57:FA:11:21:5F:04:FF:A5:16:AE:61:95:9A:B2:B2':
   {'cert': <ripe.atlas.sagan.ssl.Certificate object at 0x7fdcbe352750>,
    'cnt': 2,
    'probes': [12318, 12443]},
 u'BE:9E:83:54:86:12:70:4C:E3:18:7F:E4:53:F8:73:B2:05:B3:9D:7B:4E:7C:19:A9:05:27:B7:4E:05:F3:9E:5F':
   {'cert': <ripe.atlas.sagan.ssl.Certificate object at 0x7fdcbe352710>,
    'cnt': 2,
    'probes': [12318, 12443]}
}
```

Given this, now I trivially state that if a certificate is seen by a number of probes < 80% of the most seen (`415`) then it's declared incosistent. How can this be improved and aligned to the Atlas UI?

**Comment by astrikos** [comment]
I think we are okay for now with this one.
