### ISSUE TITLE
probe-search --center does not accept negative latitude

### ISSUE THREAD

**Issue by yang-dev** [RIPE-NCC/ripe-atlas-tools#187]
negative latitude rejected with `expected one argument`
> $ ripe-atlas probe-search --center '-17.412159,-57.264528' --radius 200
> Usage: ripe-atlas probe-search [-h] [--asn asn] [--asnv4 asnv4]
>                                [--asnv6 asnv6] [--prefix prefix]
>                                [--prefixv4 prefixv4] [--prefixv6 prefixv6]
>                                [--location location | --center center | --country country]
>                                [--radius radius] [--tag tag] [--limit limit]
>                                [--field {id,address_v6,description,is_public,coordinates,prefix_v4,asn_v6,prefix_v6,asn_v4,status,country,address_v4,is_anchor}]
>                                [--aggregate-by {country,asn_v4,asn_v6,prefix_v4,prefix_v6}]
>                                [--all]
>                                [--max-per-aggregation max_per_aggregation]
>                                [--ids-only] [--status {0,1,2,3}]
> ripe-atlas probe-search: error: argument --center: expected one argument

positive latitude works
> $ ripe-atlas probe-search --center '17.412159,-57.264528' --radius 200
> 
> Filters:
>   Radius: 17.412159,-57.264528:200
> 
> ID    Asn_v4 Asn_v6 Country Status
> ===========================================
> ===========================================
>               Showing all of 0 total probes

**Comment by danielquinn** [comment]
This is the age-old problem of the shell inturpretting `-` as referencing a command argument.  There's a few workarounds for this, but [from what I've found](https://stackoverflow.com/questions/14693718/how-to-parse-positional-arguments-with-leading-minus-sign-negative-numbers-usi) none of them work for our case.

**Comment by wadem** [comment]
This issue can be worked around using the below format;
`./ripe-atlas probe-search --center ' -33.8688,151.2093'`

Note the space after the `'` and before the `-`. 

Does the trick

**Comment by danielquinn** [comment]
Very clever!  I never would have thought of that.  Nice.

**Comment by chrisamin** [comment]
1c42029e511a99ce625436424583e42ed77816ab added note to --help text about using --center= instead of --center<space>
