### ISSUE TITLE
inconsistent releases

### ISSUE THREAD

**Issue by jnbr** [RIPE-NCC/ripe-atlas-tools#196]
Hello,

I'm maintaining the ripe-atlas-tools package for voidlinux.
Until now, I used the released files from github: https://github.com/RIPE-NCC/ripe-atlas-tools/releases

The last few releases did not show up there, so I switched to the releases on pypi.
The last pypi releases is missing the file `ripe-atlas-bash-completion.sh`.

It would be nice to have a single source for a complete release again.

**Comment by chrisamin** [comment]
Hello,

I have published a source code release on github for v2.2.3. We'll make sure to keep the releases on github up to date. Please let me know if you have any issues.

As far as I know ripe-atlas-bash-completion.sh has never been present in the packages published to pip, but I may be wrong.
