### ISSUE TITLE
pinned versions of cousteau and sagan causing warnings

### ISSUE THREAD

**Issue by aabdnn** [RIPE-NCC/ripe-atlas-tools#198]
The current version of the tools package asks for version 1.4 of cousteau and 1.2 of sagan. However, cousteau is now at 1.4.2 and sagan at 1.2.2, so pip emits warnings. Could you fix this by specifying minimum versions of the dependencies, rather than exact versions?

**Comment by chrisamin** [comment]
I have changed the requirements in setup.py to:

        "ripe.atlas.cousteau>=1.4,<2",
        "ripe.atlas.sagan>=1.2,<2",

This is in master, and by default will be packaged whenever we next make a release.

**Comment by aabdnn** [comment]
@astrikos I don't mind if exact versions are used, but it's annoying when one is updated, but another package has pinned to an older version, and then package managers emit warnings.
