### ISSUE TITLE
make --target <target> optional if a hostname/ip is given as last (and only) positional argument

### ISSUE THREAD

**Issue by emileaben** [RIPE-NCC/ripe-atlas-tools#206]
in stock traceroute 1.2.3.4  is understood as meaning that the target of the measurement is 1.2.3.4
in ripe-atlas-tools you have to define --target <target> to specify a measurement target.

i'd like ripe-atlas-tools to work more like stock traceroute, ie. use like this:
ripe-atlas measure traceroute 1.2.3.4

**Comment by chrisamin** [comment]
This will be a feature of v3.0.0.0. Each command can have a primary positional argument assigned which acts as an alias for its mandatory --optional arg. For the measure commands this is "--target" except for "dns" where it is "--query-argument".
