### ISSUE TITLE
Allow to pass the API key as an environment variable

### ISSUE THREAD

**Issue by gfa** [RIPE-NCC/ripe-atlas-tools#210]
Hello

currently the api key has to be saved on disk, unencrypted, I don't think is a great practice.

could you support to take the api key for an environmental variable? or even better from the output of a command. That way the configuration file will be clean of secrets and it can be versioned, stored, etc.

thanks!

**Comment by chrisamin** [comment]
Available in v3.0.0, uses ATLAS_FETCH_KEY or ATLAS_CREATE_KEY if available, otherwise falls back to config
