### ISSUE TITLE
OpenAPI spec file/swagger

### ISSUE THREAD

**Issue by Pflanzgurke** [RIPE-NCC/ripe-atlas-tools#212]
Hi,

is the API OpenAPI compatible/generated, and if yes, would it be possible to get the spec file to generate client code on swagger? Or is it already there and I was just incapable of finding it?

**Comment by chrisamin** [comment]
Yes, it's OpenAPI/Swagger v1.2, available here: https://atlas.ripe.net/docs/api/v2/reference/api-docs
