### ISSUE TITLE
Accept JSON specification to create a measurement

### ISSUE THREAD

**Issue by PhilipHomburg** [RIPE-NCC/ripe-atlas-tools#216]
The primary use case is to have a command that creates a measurement and returns results as well.

Using the API that requires one call the create the measurement and a separate command that listens to the stream.

Accepting JSON as input allows everything that the API allows without figuring how to pass that as command line options.

**Comment by chrisamin** [comment]
I think this is a good idea. Would you see this as something to be combined with the command line options, so you can specify a base JSON spec but also override a few options? And what about probe sources?

**Comment by PhilipHomburg** [comment]
Overriding the spec is fine, but is not my primary use case.

I think probe sources should be independent of the measurement spec. So it would be fine to create a similar option for probe sources, but it should be possible to use command line options for the probe sources as well.

**Comment by chrisamin** [comment]
Available in v3.0.0
