### ISSUE TITLE
yaml.load error at every launch

### ISSUE THREAD

**Issue by dominix** [RIPE-NCC/ripe-atlas-tools#225]
every time I use command line ripe-atlas I got an error message.

`
/usr/local/lib/python3.8/dist-packages/ripe/atlas/tools/settings/__init__.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, /usr/local/lib/python3.8/dist-packages/ripe/atlas/tools/settings/__init__.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  custom = yaml.load(y)
as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  custom = yaml.load(y)
`
dunno why, can someone fix this ?

**Comment by dominix** [comment]
ripe-atlas-tools was installed with pip3 as system wide. 
`sudo -H pip3 install ripe-atlas-tools `

**Comment by robert-kisteleki** [comment]
I tried reproducing this on Mac OSX, using a fresh install using Python 3.8.9 and Python 3.9.4 and fresh venvs. The pip install pulled PyYAML-5.4.1 which *should* (according to https://msg.pyyaml.org/load) also have this issue, but I did not see it.

Ultimately, the tool should be updated to moved on from the deprecated call. A PR would be welcome :-)

**Comment by lamehost** [comment]
Is this the same as of #213 ?

**Comment by EnterChaser** [comment]
Lave a Comand

**Comment by chrisamin** [comment]
Fixed in v3.0.0
