### ISSUE TITLE
Parsing /etc/os-release for User Agent?

### ISSUE THREAD

**Issue by RaitoBezarius** [RIPE-NCC/ripe-atlas-tools#231]
Hi there, I am in the process of packaging this tool in nixpkgs/NixOS, and we were wondering regarding the user agent aspect (according to https://github.com/RIPE-NCC/ripe-atlas-tools/blob/master/docs/packaging.rst) if it could be possible to parse `/etc/os-release` as this is a XDG standard (https://www.freedesktop.org/software/systemd/man/os-release.html / https://docs.python.org/3/library/platform.html#platform.freedesktop_os_release), I understand this could be specific to the Linux world, so that's more a suggestion to open up multiple ways to read the user agent, which could be all ultimately overridden by the user-agent file.

As I would love to use the proper user agent on nixpkgs/NixOS, but, as our versions are very fine-grained and freeze the state of all packages currently in nixpkgs (the githash), injecting it as you suggest it would cause systematic rebuilds to the package just to update the user agent file, which would be a waste of CI / disk resources.

Let me know your thoughts and of course this is only a naive question and a proposal :). Thanks again for your work!

**Comment by chrisamin** [comment]
Using os-release when present maskes sense. We're already using XDG_CONFIG_HOME when present. My proposal is to fall back to a string like "RIPE Atlas Tools [PRETTY_NAME] 3.0.0". The PRETTY_NAME equivalent would be taken from Python's "platform" module for OS X and Windows. "platform" actually includes XDG support in the latest version but we'll need a shim for now. Does this sound like it would suit  your use case?

**Comment by RaitoBezarius** [comment]
> Using os-release when present makes sense. We're already using XDG_CONFIG_HOME when present. My proposal is to fall back to a string like "RIPE Atlas Tools [PRETTY_NAME] 3.0.0". The PRETTY_NAME equivalent would be taken from Python's "platform" module for OS X and Windows. "platform" actually includes XDG support in the latest version but we'll need a shim for now. Does this sound like it would suit your use case?

That would be great indeed!

**Comment by chrisamin** [comment]
This has been applied in v3.0.0
