### ISSUE TITLE
Feature request: —limit on streaming after measurement creation.

### ISSUE THREAD

**Issue by Ernst2020** [RIPE-NCC/ripe-atlas-tools#238]
After a measurement is created, automatically streaming the results is started.
With streaming the results of an existing measurement the “—limit” option is available. Reporting then stops after that many results.

Please consider including this option also for the streaming part of the measurement creation command. If we only need a couple results then we don’t have to wait the hard coded 5 minutes.

The stream command has this option, but it cannot be specified for the automatic streaming after a measurement has been created. Thus, it seems a small task to include this option in the “measure” command.

Thanks.

**Comment by chrisamin** [comment]
309bdc56da5bca0f20d76921ecc193031137de57 adds --stream-limit and --stream-timeout to measure command, so you can wait for e.g. 3 out of 5 probes with "--probes 5 --stream-limit 3". Does this do what you want?

**Comment by Ernst2020** [comment]
Yes! Thanks. I will add this change in the meantime to my “base.py” code. 

Excellent. Thank you Chris.
