### ISSUE TITLE
Using the renderers with external data

### ISSUE THREAD

**Issue by spakka** [RIPE-NCC/ripe-atlas-tools#26]
So at the moment, the tools don't have a sense of time, they always return the latest result.
If I want to see previous data, I've probably had to get it from the API or the download part of the UI, which means I have a blob of JSON (in my case a traceroute) in a file. In my case, it's a day's worth of data from a probe's built-in DNS and traceroute measurements.
What would be awesome is to be able to pipe that file into the appropriate renderer, to turn it into something that is easy to read :)

Using the tool as a parser for any Atlas JSON seems to me like a use case, so if you have already retrieved some JSON, the tool can be used to render it.

**Comment by astrikos** [comment]
Additionally we could specify stop/start time on the command line and tool will fetch data and apply all renderer options. [Cousteau](https://github.com/RIPE-NCC/ripe-atlas-cousteau) has already support for this, so it should be easy enough.
But I agree piping or reading from given file is a handy option as well.

**Comment by spakka** [comment]
I've opened that as a separate request #27 
As they are two separate questions :)

**Comment by danielquinn** [comment]
I'm going to start tinkering with this one today.  I was thinking the following syntax unless there are objections:

```bash
$ cat /path/to/file | ripe-atlas render [--renderer renderer_name]
```

or

```bash
$ ripe-atlas render [--renderer renderer_name] [--from-file /path/to/file]
```

If there are objections, speak now, or forever hold your peace.

**Comment by spakka** [comment]
works for me :)

**Comment by pierky** [comment]
:+1:
