### ISSUE TITLE
Missing defaults in DNS measurements

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/ripe-atlas-tools#4]

**Comment by bortzmeyer** [comment]
[Sorry, issue created too fast, the body was missing.]

Creating a DNS measurement requires too many options. We should have sensible values:

For the target, use-probe-resolver should be the default

For the class, IN must be a default value

For the qtype, I guess A would be a nice default (the same as dig or drill), or AAAA to be more modern.

**Comment by danielquinn** [comment]
The `query-class` and `query-type` were always defaulted to in `IN` and `A`, but the help text didn't really make that clear, so I fixed that up.  I then changed the code to allow users to not specify a target and have that assume that they want to use the probe's resolver.
