### ISSUE TITLE
Report give traceback if measurement_id is invalid

### ISSUE THREAD

**Issue by cod3monk** [RIPE-NCC/ripe-atlas-tools#51]
```
$ ripe-atlas report 1
Traceback (most recent call last):
  File "/Users/codemonk/python/bin/ripe-atlas", line 77, in <module>
    sys.exit(RipeAtlas().main())
  File "/Users/codemonk/python/bin/ripe-atlas", line 68, in main
    ).Command(*self.args, **self.kwargs).run()
  File "/Users/codemonk/python/lib/python2.7/site-packages/ripe/atlas/tools/commands/report.py", line 56, in run
    formatter_instance = Report.get_formatter(detail["type"]["name"])()
TypeError: string indices must be integers
$
```

A useful error message would be much appreciated ;)

**Comment by astrikos** [comment]
Hi @cod3monk, 
I can't reproduce that with the code we have in master. I suppose you install it with pip install from pypi right? So, you probably have a very old version. Could you try installing it from github

    pip install -e git+https://github.com/RIPE-NCC/ripe-atlas-tools.git#egg=ripe.atlas.tools

And tell me what you get?

**Comment by cod3monk** [comment]
Yes, it is fixed. I was on the pypi version.
