### ISSUE TITLE
Allow options for reports

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#7]
We need a way to make reports a little more customised.  like --use-hostname or --use-asn

**Comment by pierky** [comment]
I would suggest using a local cache to store IP-address/ASN mappings, something similar to my [ipdetailscache](https://github.com/pierky/ipdetailscache) library (it gathers info from RIPEStat API), in order to speed up resolution/rendering of reports. Mine depends on Google Python IP address manipulation library (ipaddr) that would be another dependency to be added to the list. A new one built on IPy would be better IMHO.
@danielquinn: if I'm not mistaken you wrote a similar cache too, right?

**Comment by danielquinn** [comment]
I don't have a cache like this, but I believe that one of us over here does.  Your suggestion is a good one though.  Currently, the reports aren't smart enough to do IP/ASN lookups, but when they do, a unified caching framework within the tool should be there.

**Comment by emileaben** [comment]
Yes, I did write a similar cache that does lookups in Ripestat and
Openipmap for both ASN and geolocation lookups:
https://github.com/emileaben/ixp-country-jedi/blob/master/lib/Atlas/IPInfoCache.py

prototype, but it works. could probably be improved by some code from Pier
Carlo Chiodi (private range IPs etc.), as well as using a Radix structure
to cache prefixes, instead of single IPs for IP2AS type lookups.

**Comment by danielquinn** [comment]
I added [a simple cache system](https://github.com/RIPE-NCC/ripe-atlas-tools/blob/master/ripe/atlas/tools/cache.py) today that to which we can apply your asn/geolocation/ipwhatever lookups.  Basically the interface is like this:

```python
from ripe.atlas.tools.cache import cache

my_cache_time = 3600
cache.set("my-cache-key", "my value", my_cache_time)
cache.get("my-cache-key")  # returns None if the value has expired
```

It's totally untested at this point, but I just wanted to keep you guys in the loop.

**Comment by pierky** [comment]
In the meanwhile I pushed a testing branch of my ipdetailscache where I added support for IPy: https://github.com/pierky/ipdetailscache/commit/5481d5161d128cab968a7c4b2e8d76ddf95da249

**Comment by astrikos** [comment]
Wouldn't it be better if we use a memoize decorator for that??https://wiki.python.org/moin/PythonDecoratorLibrary#Memoize
I am not really sure I need yet another file on my system. You would cache ofcourse per single process, but I am not convinced it would be much different in our purpose.
A decorator would also be cleaner and more pythonic way to do stuff :)

**Comment by danielquinn** [comment]
I like this pattern, but I also think it should be combined with the caching engine I've already added.  The key here is that the goal is to be able to cache output from these methods *for future requests* so that they don't need to be done again.  Since IP:ASN mappings (for example) don't change very often, it makes sense to have a persistent cache file for this sort of thing.

But making use of it in a decorator-like fashion, that's much cleaner than the whole `cache.set()` thing.  I shall make it go exactly like that.

**Comment by danielquinn** [comment]
After a chat with Robert, it looks like we're going to introduce *global* aggregate options that may or may not be available to a given renderer.  I'm still working out what this will look like code-wise, but in terms of user-interface:

    # Group the output by country
    ripe-atlas report <measurement-id> --aggregate=country

    # Group the output by asn
    ripe-atlas report <measurement-id> --aggregate=asn

This will require a lot more work on the side of the renderer, and since I don't want to have to repeat code anywhere, I may code this into the parent `Renderer` class so that subclasses can make use of it somehow.  We'll see how that goes.

**Comment by robert-kisteleki** [comment]
I'd indeed love to see that kind of aggregation. It cold be applicable to new measurements as well as fetching results of older ones. So in addition to the above, this could work too:

    ripe-atlas ping whatever.com --aggregate=country

It would give you the same thing, based on the just-collected results. If the msm spec happens to restrict probes to a single country, then it'll be a one-liner output...

**Comment by astrikos** [comment]
@danielquinn I think it would make sense to detach aggregator logic from renderer. The best route for me would be to create Aggregator class/function and apply it to results before you render them. thoughts?

**Comment by danielquinn** [comment]
@astrikos this could work actually.  We could create string-like objects to represent each row, and then catch the output, rendering it one way or another based on these flags.

Yeah that might do nicely.

**Comment by emileaben** [comment]
Will that work in cases where the aggregation is renderer-specific? ie. if
I write a renderer that I want to aggregate-by-country , but the aggregator
logic (Aggregator class) hides the information i need for my renderer, how
do i get to the raw information?
I'd all be for a Aggregator class that can be overridden by the renderer,
so it still can access the raw results if needed.
but maybe i'm misunderstanding.

**Comment by danielquinn** [comment]
@emileaben I think I'd need to see a more detailed use case for something like this, but let's keep things simple to start?

**Comment by emileaben** [comment]
agree. simple imho would be not abstract away too much from the renderers
(as you may limit the ability of renderers)

**Comment by astrikos** [comment]
I think we can close this one, anyone wants to add anything more?
