### ISSUE TITLE
Custom multiple configurations

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#8]
We want a way to allow someone to invoke ripe-atlas with `--config /path/to/config`

**Comment by astrikos** [comment]
Is that still relevant? Not sure anyone really needs it, especially after last @pierky  additions for alias fetch keys.

**Comment by danielquinn** [comment]
It's probably still relevant for people who'd like to create measurements with different sets of defaults, but as I've not seen people calling for it, I don't think it's a feature high on the list of priorities.

**Comment by chrisamin** [comment]
Closing, not implementing unless there are more requests/more specification.
