### ISSUE TITLE
support for refering to a measurement by a locally defined name

### ISSUE THREAD

**Issue by emileaben** [RIPE-NCC/ripe-atlas-tools#92]
i can't remember all the measurement ids for measurements i've created, but i can remember them by short names. it would be great if the tools could help me find my measurement back by storing short names.

ie. 
instead of
ripe-atlas report 123456789
i could say
ripe-atlas report my-cool-ipv6-measurement

and there would be a local cache of <name>->msm_id mappings

**Comment by danielquinn** [comment]
After a conversation with @emileaben and @phicoh, it looks like this is really more a question of measurement tagging than local naming.  They want to be able to create measurements with attached tags and then later query all measurements with a single tag.

As this is really a server-side infrastructure question more than a local command-line thing, this can't be a priority for Magellan until that aspect is worked out on the server.
