### ISSUE TITLE
Don't wait for results forever

### ISSUE THREAD

**Issue by robert-kisteleki** [RIPE-NCC/ripe-atlas-tools#98]
Listening to the result stream should stop after I get all the results.

For bonus points: the user could specify "stop after getting X results" or "stop after getting X% of the results" as well as "time out after X seconds [after the last received result]"

**Comment by astrikos** [comment]
From what I see this is supported in cases where user specifies probes as argument. So in cases of 'ripe-atlas report --probes=1,2,3' it will exit after 3 results. 
It should be easy to add same behaviour with an additional argument.

**Comment by robert-kisteleki** [comment]
measure --from-probes does not have this behaviour
measure --probes X does, it exits after receiving X results

Perhaps the best thing to do is to implement "stop after getting X results" and as a default set X to the number of probes specified.

**Comment by danielquinn** [comment]
The code is written to use the value of `--probes` (which always has a value, even if it's the default).  It uses this in conjunction with a (currently) hard-coded [timeout of 5 minutes](https://github.com/RIPE-NCC/ripe-atlas-tools/blob/master/ripe/atlas/tools/commands/measure/base.py#L244).  This means that it will wait for results for a maximum of 5 minutes *resetting the timer after every packet*.

If this does not appear to be the actual behaviour, then I'd consider this a bug, but if you think this behaviour should be different, then I can tweak it some way.

**Comment by robert-kisteleki** [comment]
I asked for 3 probes using --from-probes and I got three results. I was happy, but the script kept on waiting for more results.

**Comment by danielquinn** [comment]
Hmm.  Alright well that's clearly a bug then.  If the expected behaviour is cool with you, then I'll just find and squish the bug then.

**Comment by danielquinn** [comment]
Well this sucks.  I can't reproduce it.  This is using the `master` branch:

```
$ ripe-atlas measure ping --target danielquinn.org --probes 3

Looking good!  Your measurement was created and details about it can be found here:

  https://atlas.ripe.net/measurements/2957927/


Connecting to stream...

48 bytes from probe #11334 212.185.87.38   to 37.58.75.249 (37.58.75.249): ttl=56 times:17.64,   17.249,  17.189, 
48 bytes from probe #11421 178.3.134.153   to 37.58.75.249 (37.58.75.249): ttl=54 times:24.725,  23.49,   24.388, 
48 bytes from probe #16265 37.24.137.141   to 37.58.75.249 (37.58.75.249): ttl=52 times:26.975,  26.79,   27.317, 

Disconnecting from stream

You can find details about this measurement here:

  https://atlas.ripe.net/measurements/2957927/
```

**Comment by astrikos** [comment]
No, using --probes does the job, it's when user specifies --from-probes. You would expect that since we know indirectly number of probes it would exit as well, but it doesn't.
Also, since we always know the number of requested probes it makes sense for the tool to exit as soon as we get the same number of results.

**Comment by danielquinn** [comment]
Ah I see.  Alright then I'll have to force `self.arguments.probes = len(self.arguments.from_probes)` when `from_probes` is set.  I think that should do it.
